image: build1.dev.nids.noaa.gov:5000/build/nodejs-rhel7

stages:
    - build
    - deploy

build:
    stage: build
    only:
        - /^bugfix\//
        - /^feature\//
        - master
    script:
        - make test
        - make package
    artifacts:
        paths:
            - dist/*.tar.gz

deploy:local:
    stage: deploy
    only:
        - tags
    script:
        - test "${CI_BUILD_TAG}" == "$(node -e 'console.log(JSON.parse(fs.readFileSync("./package.json", "utf8"))["version"]);')"
        - make publish
        - make package
        - scp dist/*.tar.gz ${CDN_DEV_UPLOAD_LOGIN}:${CDN_DEV_UPLOAD_PATH}
    artifacts:
        paths:
            - dist/*.tar.gz
